### ISSUE TITLE
Create vector to save theta instead of void

### ISSUE THREAD

**Issue by shantiverschoor** [sam-xl/Slic3r#2]
This is maybe something really simple but I was stuck yesterday so here goes:\
The theta's calculated for every facet of the non-planar surfaced need to be stored somewhere to use in the Gcode. Something in the sence like:
`typedef std::vector<NonplanarSurface> Theta;`
but this gives an error when I try to push.back(calculate_theta). I tried to follow the example for `group_surfaces` but that did not work. Does anybody know how to solve this?\
That's not everything: before all the values are stored (there are a lot of theta's) I need to loop through them and look if the next theta is not "almost" the same as the original one, because otherwise it will generate too much thetas to use in the gcode with the same value.

**Comment by shantiverschoor** [comment]
Update: typedef not the correct way to declare a theta vector, so it's removed. Updated branch contains new `calculate_theta` inside NonplanarSurfaces.cpp. This time, only the first angle of the facet is calculated and outputed as a float called `theta`.  This is done to simplify code, to use only this one theta as an example to generate the Gcode with.

**Comment by dave992** [comment]
A `typedef` is an way to create an alias for your types. Usefull if you use a type often and its very long due to namespaces or something. It does not actually create a variable, you still have to do that yourself (but you can then use this new type). 

Can you please link to the code or copy in the code snipped in the issue instead of giving the filename? GitHub/GitLab allow to visualize code snippets quite easily: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by shantiverschoor** [comment]
Of course, I'll show the code here: this is line 197-204 in NonplanarSurface.cpp
``` cpp
void
NonplanarSurface::calculate_theta(){
    // the first facet gets a theta value (for now, can be looped over all facets)
    //if surface is flat (test airfoil) use the first facet's theta as surface theta
    //for more complicated surfaces, you need to do something with multiple thetas (tbc)
 auto facet = this->mesh.begin();
    this->theta = std::acos((facet->second.dot_product/(facet->second.maga*facet->second.magb))); 
    std::cout << this->theta;
```
this is now sending one theta value from mesh.begin(), to test if this code makes sence to use for the gcodewriter.cpp. But you want to send multiple values of this angle if the part is more complex. So I want to store this in a vector (where theta[1 ]= facet[1]) and then do calculations with it to determine theta is needed from this facet (oversimplification of course). If it is necessary to make a typedef, what else do I need to do with it? Or do you see another way to do this?

**Comment by shantiverschoor** [comment]
Example group surfaces:
```cpp

NonplanarSurfaces
NonplanarSurface::group_surfaces()
{
    std::pair<int, NonplanarFacet> begin = *this->mesh.begin();
    this->mark_neighbor_surfaces(begin.first);
    NonplanarSurface newSurface;
    for (std::map<int, NonplanarFacet>::iterator it=this->mesh.begin(); it!=this->mesh.end();) {
        if((*it).second.marked == false) {
            newSurface.mesh[(*it).first] = (*it).second;
            it = this->mesh.erase(it);
        }
        else {
            ++it;
        }
    }
    this->calculate_stats();
    if (newSurface.mesh.size() == 0) {
        //return only this
        NonplanarSurfaces nonplanar_surfaces;
        nonplanar_surfaces.push_back(*this);
        return nonplanar_surfaces;
    }
    else {
        //return union of this and recursion
        NonplanarSurfaces nonplanar_surfaces = newSurface.group_surfaces();
        nonplanar_surfaces.push_back(*this);
        return nonplanar_surfaces;
    }
}
```

**Comment by shantiverschoor** [comment]
I think this issue is solved, a lot of this of this issue was due to me not understanding C++ so much. If still interested in how this is solved. Look at the code in NonplanarSurfaces.cpp, line 234: 
```
    for(auto& facet : this->mesh){
        facet.second.a[0] = facet.second.N[0];
        facet.second.a[1] = facet.second.N[1];
        facet.second.a[2] = facet.second.N[2];
        facet.second.b[0] = 0;
        facet.second.b[1] = 0;
        facet.second.b[2] = 1;
        facet.second.dot_product = facet.second.a[0]*facet.second.b[0] +facet.second.a[1]*facet.second.b[1]+facet.second.a[2]*facet.second.b[2];
        facet.second.maga = std::sqrt(facet.second.a[0]*facet.second.a[0]+facet.second.a[1]*facet.second.a[1]+facet.second.a[2]*facet.second.a[2]);
        facet.second.magb = std::sqrt(facet.second.b[0]*facet.second.b[0]+facet.second.b[1]*facet.second.b[1]+facet.second.b[2]*facet.second.b[2]);
    
        std::ofstream myfile;
        std::stringstream stream;
        myfile.open ("/home/shantiverschoor/workspaces/Slic3r/thetas_loop.txt", std::ios_base::app);
        this->theta = -180* std::acos((facet.second.dot_product/(facet.second.maga*facet.second.magb)))/3.14159265;
        stream <<std::fixed <<this->theta<<"\n";
        myfile <<stream.str();
        myfile.close();
```
Function called in PrintObject (line 1216)
```

            // shanti adding theta
            for (auto& surface : this->nonplanar_surfaces)
            {
                surface.calculate_normal();
                surface.calculate_theta();
                surface.mag();
                surface.dot_product();
```
